# Disable sudo to speed up the build
sudo: false

dist: xenial

# Set the build language to Python
language: python

python: 3.7

# Install the codecov pip dependency
install:
  - pip install codecov

# Run the unit test
script:
  - coverage run tests.py

# Push the results back to codecov
after_success:
- codecov
